export const siteConfig = {
  name: "Chanatip Sombatanurak | Developer Portfolio",
  authorName: "Chanatip Sombatanurak",
  username: "chanatipsombatanurak",
  description:
    "Chanatip Sombatanurak's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://yonnpee-app.vercel.app",
  links: {
    linkedin: "https://www.linkedin.com/in/chanatip-sombatanurak-9a17b9388",
    github: "https://github.com/yoonpee-github",
  },
  ogImage: "https://yonnpee-app.vercel.app/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Chanatip Sombatanurak",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
